#import "./photoField.gql"
#import "./userField.gql"
query Search($type:String,$keyword:String,$first:Int!,$after:ID){
  search(type:$type,keyword:$keyword,first:$first,after:$after) {
    keyword
    type
    first
    after
    isEnd
    list{
     id
     content
     type
     thumbnail{
       ...PhotoField
     }
     photos{
       ...PhotoField
     }
     user{
      ...UserField
     }
    }
  }
}