#import "./photoField.gql"
#import "./userField.gql"
query Subscribe($first:Int!,$after:ID){
  subscribe(first:$first,after:$after) {
    first
    after
    isEnd
    list{
     id
     content
     type
     thumbnail{
       ...PhotoField
     }
     photos{
       ...PhotoField
     }
     user{
      ...UserField
     }
    }
  }
}