#import "./userField.gql"

query Users($keyword:String,$first:Int!,$after:ID){
  users(keyword:$keyword,first:$first,after:$after){
    keyword
    first
    after
    isEnd
    list{
      ...UserField
    }
  }
}